package org.example.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class QueryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public QueryExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidIsNull() {
            addCriterion("characteristicvalueresiduaid is null");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidIsNotNull() {
            addCriterion("characteristicvalueresiduaid is not null");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidEqualTo(Integer value) {
            addCriterion("characteristicvalueresiduaid =", value, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidNotEqualTo(Integer value) {
            addCriterion("characteristicvalueresiduaid <>", value, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidGreaterThan(Integer value) {
            addCriterion("characteristicvalueresiduaid >", value, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("characteristicvalueresiduaid >=", value, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidLessThan(Integer value) {
            addCriterion("characteristicvalueresiduaid <", value, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidLessThanOrEqualTo(Integer value) {
            addCriterion("characteristicvalueresiduaid <=", value, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidIn(List<Integer> values) {
            addCriterion("characteristicvalueresiduaid in", values, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidNotIn(List<Integer> values) {
            addCriterion("characteristicvalueresiduaid not in", values, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidBetween(Integer value1, Integer value2) {
            addCriterion("characteristicvalueresiduaid between", value1, value2, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andCharacteristicvalueresiduaidNotBetween(Integer value1, Integer value2) {
            addCriterion("characteristicvalueresiduaid not between", value1, value2, "characteristicvalueresiduaid");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeIsNull() {
            addCriterion("productgroupcode is null");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeIsNotNull() {
            addCriterion("productgroupcode is not null");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeEqualTo(String value) {
            addCriterion("productgroupcode =", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeNotEqualTo(String value) {
            addCriterion("productgroupcode <>", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeGreaterThan(String value) {
            addCriterion("productgroupcode >", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeGreaterThanOrEqualTo(String value) {
            addCriterion("productgroupcode >=", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeLessThan(String value) {
            addCriterion("productgroupcode <", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeLessThanOrEqualTo(String value) {
            addCriterion("productgroupcode <=", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeLike(String value) {
            addCriterion("productgroupcode like", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeNotLike(String value) {
            addCriterion("productgroupcode not like", value, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeIn(List<String> values) {
            addCriterion("productgroupcode in", values, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeNotIn(List<String> values) {
            addCriterion("productgroupcode not in", values, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeBetween(String value1, String value2) {
            addCriterion("productgroupcode between", value1, value2, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andProductgroupcodeNotBetween(String value1, String value2) {
            addCriterion("productgroupcode not between", value1, value2, "productgroupcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeIsNull() {
            addCriterion("bomcode is null");
            return (Criteria) this;
        }

        public Criteria andBomcodeIsNotNull() {
            addCriterion("bomcode is not null");
            return (Criteria) this;
        }

        public Criteria andBomcodeEqualTo(String value) {
            addCriterion("bomcode =", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeNotEqualTo(String value) {
            addCriterion("bomcode <>", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeGreaterThan(String value) {
            addCriterion("bomcode >", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeGreaterThanOrEqualTo(String value) {
            addCriterion("bomcode >=", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeLessThan(String value) {
            addCriterion("bomcode <", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeLessThanOrEqualTo(String value) {
            addCriterion("bomcode <=", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeLike(String value) {
            addCriterion("bomcode like", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeNotLike(String value) {
            addCriterion("bomcode not like", value, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeIn(List<String> values) {
            addCriterion("bomcode in", values, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeNotIn(List<String> values) {
            addCriterion("bomcode not in", values, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeBetween(String value1, String value2) {
            addCriterion("bomcode between", value1, value2, "bomcode");
            return (Criteria) this;
        }

        public Criteria andBomcodeNotBetween(String value1, String value2) {
            addCriterion("bomcode not between", value1, value2, "bomcode");
            return (Criteria) this;
        }

        public Criteria andEpnumberIsNull() {
            addCriterion("epnumber is null");
            return (Criteria) this;
        }

        public Criteria andEpnumberIsNotNull() {
            addCriterion("epnumber is not null");
            return (Criteria) this;
        }

        public Criteria andEpnumberEqualTo(Integer value) {
            addCriterion("epnumber =", value, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberNotEqualTo(Integer value) {
            addCriterion("epnumber <>", value, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberGreaterThan(Integer value) {
            addCriterion("epnumber >", value, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("epnumber >=", value, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberLessThan(Integer value) {
            addCriterion("epnumber <", value, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberLessThanOrEqualTo(Integer value) {
            addCriterion("epnumber <=", value, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberIn(List<Integer> values) {
            addCriterion("epnumber in", values, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberNotIn(List<Integer> values) {
            addCriterion("epnumber not in", values, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberBetween(Integer value1, Integer value2) {
            addCriterion("epnumber between", value1, value2, "epnumber");
            return (Criteria) this;
        }

        public Criteria andEpnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("epnumber not between", value1, value2, "epnumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberIsNull() {
            addCriterion("ordernumber is null");
            return (Criteria) this;
        }

        public Criteria andOrdernumberIsNotNull() {
            addCriterion("ordernumber is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernumberEqualTo(Integer value) {
            addCriterion("ordernumber =", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberNotEqualTo(Integer value) {
            addCriterion("ordernumber <>", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberGreaterThan(Integer value) {
            addCriterion("ordernumber >", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordernumber >=", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberLessThan(Integer value) {
            addCriterion("ordernumber <", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberLessThanOrEqualTo(Integer value) {
            addCriterion("ordernumber <=", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberIn(List<Integer> values) {
            addCriterion("ordernumber in", values, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberNotIn(List<Integer> values) {
            addCriterion("ordernumber not in", values, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberBetween(Integer value1, Integer value2) {
            addCriterion("ordernumber between", value1, value2, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberNotBetween(Integer value1, Integer value2) {
            addCriterion("ordernumber not between", value1, value2, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberIsNull() {
            addCriterion("eporiginalnumber is null");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberIsNotNull() {
            addCriterion("eporiginalnumber is not null");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberEqualTo(Integer value) {
            addCriterion("eporiginalnumber =", value, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberNotEqualTo(Integer value) {
            addCriterion("eporiginalnumber <>", value, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberGreaterThan(Integer value) {
            addCriterion("eporiginalnumber >", value, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("eporiginalnumber >=", value, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberLessThan(Integer value) {
            addCriterion("eporiginalnumber <", value, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberLessThanOrEqualTo(Integer value) {
            addCriterion("eporiginalnumber <=", value, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberIn(List<Integer> values) {
            addCriterion("eporiginalnumber in", values, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberNotIn(List<Integer> values) {
            addCriterion("eporiginalnumber not in", values, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberBetween(Integer value1, Integer value2) {
            addCriterion("eporiginalnumber between", value1, value2, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andEporiginalnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("eporiginalnumber not between", value1, value2, "eporiginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberIsNull() {
            addCriterion("orderoriginalnumber is null");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberIsNotNull() {
            addCriterion("orderoriginalnumber is not null");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberEqualTo(Integer value) {
            addCriterion("orderoriginalnumber =", value, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberNotEqualTo(Integer value) {
            addCriterion("orderoriginalnumber <>", value, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberGreaterThan(Integer value) {
            addCriterion("orderoriginalnumber >", value, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderoriginalnumber >=", value, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberLessThan(Integer value) {
            addCriterion("orderoriginalnumber <", value, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberLessThanOrEqualTo(Integer value) {
            addCriterion("orderoriginalnumber <=", value, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberIn(List<Integer> values) {
            addCriterion("orderoriginalnumber in", values, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberNotIn(List<Integer> values) {
            addCriterion("orderoriginalnumber not in", values, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberBetween(Integer value1, Integer value2) {
            addCriterion("orderoriginalnumber between", value1, value2, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andOrderoriginalnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("orderoriginalnumber not between", value1, value2, "orderoriginalnumber");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityIsNull() {
            addCriterion("ep_net_remaining_quantity is null");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityIsNotNull() {
            addCriterion("ep_net_remaining_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityEqualTo(Integer value) {
            addCriterion("ep_net_remaining_quantity =", value, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityNotEqualTo(Integer value) {
            addCriterion("ep_net_remaining_quantity <>", value, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityGreaterThan(Integer value) {
            addCriterion("ep_net_remaining_quantity >", value, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("ep_net_remaining_quantity >=", value, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityLessThan(Integer value) {
            addCriterion("ep_net_remaining_quantity <", value, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("ep_net_remaining_quantity <=", value, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityIn(List<Integer> values) {
            addCriterion("ep_net_remaining_quantity in", values, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityNotIn(List<Integer> values) {
            addCriterion("ep_net_remaining_quantity not in", values, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityBetween(Integer value1, Integer value2) {
            addCriterion("ep_net_remaining_quantity between", value1, value2, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andEpNetRemainingQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("ep_net_remaining_quantity not between", value1, value2, "epNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityIsNull() {
            addCriterion("order_net_remaining_quantity is null");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityIsNotNull() {
            addCriterion("order_net_remaining_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityEqualTo(Integer value) {
            addCriterion("order_net_remaining_quantity =", value, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityNotEqualTo(Integer value) {
            addCriterion("order_net_remaining_quantity <>", value, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityGreaterThan(Integer value) {
            addCriterion("order_net_remaining_quantity >", value, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_net_remaining_quantity >=", value, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityLessThan(Integer value) {
            addCriterion("order_net_remaining_quantity <", value, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("order_net_remaining_quantity <=", value, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityIn(List<Integer> values) {
            addCriterion("order_net_remaining_quantity in", values, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityNotIn(List<Integer> values) {
            addCriterion("order_net_remaining_quantity not in", values, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityBetween(Integer value1, Integer value2) {
            addCriterion("order_net_remaining_quantity between", value1, value2, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andOrderNetRemainingQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("order_net_remaining_quantity not between", value1, value2, "orderNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityIsNull() {
            addCriterion("buffer_total_quantity is null");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityIsNotNull() {
            addCriterion("buffer_total_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityEqualTo(Integer value) {
            addCriterion("buffer_total_quantity =", value, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityNotEqualTo(Integer value) {
            addCriterion("buffer_total_quantity <>", value, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityGreaterThan(Integer value) {
            addCriterion("buffer_total_quantity >", value, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("buffer_total_quantity >=", value, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityLessThan(Integer value) {
            addCriterion("buffer_total_quantity <", value, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("buffer_total_quantity <=", value, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityIn(List<Integer> values) {
            addCriterion("buffer_total_quantity in", values, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityNotIn(List<Integer> values) {
            addCriterion("buffer_total_quantity not in", values, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityBetween(Integer value1, Integer value2) {
            addCriterion("buffer_total_quantity between", value1, value2, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferTotalQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("buffer_total_quantity not between", value1, value2, "bufferTotalQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityIsNull() {
            addCriterion("buffer_remaining_quantity is null");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityIsNotNull() {
            addCriterion("buffer_remaining_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityEqualTo(Integer value) {
            addCriterion("buffer_remaining_quantity =", value, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityNotEqualTo(Integer value) {
            addCriterion("buffer_remaining_quantity <>", value, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityGreaterThan(Integer value) {
            addCriterion("buffer_remaining_quantity >", value, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("buffer_remaining_quantity >=", value, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityLessThan(Integer value) {
            addCriterion("buffer_remaining_quantity <", value, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("buffer_remaining_quantity <=", value, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityIn(List<Integer> values) {
            addCriterion("buffer_remaining_quantity in", values, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityNotIn(List<Integer> values) {
            addCriterion("buffer_remaining_quantity not in", values, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityBetween(Integer value1, Integer value2) {
            addCriterion("buffer_remaining_quantity between", value1, value2, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferRemainingQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("buffer_remaining_quantity not between", value1, value2, "bufferRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityIsNull() {
            addCriterion("buffer_net_remaining_quantity is null");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityIsNotNull() {
            addCriterion("buffer_net_remaining_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityEqualTo(Integer value) {
            addCriterion("buffer_net_remaining_quantity =", value, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityNotEqualTo(Integer value) {
            addCriterion("buffer_net_remaining_quantity <>", value, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityGreaterThan(Integer value) {
            addCriterion("buffer_net_remaining_quantity >", value, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("buffer_net_remaining_quantity >=", value, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityLessThan(Integer value) {
            addCriterion("buffer_net_remaining_quantity <", value, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("buffer_net_remaining_quantity <=", value, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityIn(List<Integer> values) {
            addCriterion("buffer_net_remaining_quantity in", values, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityNotIn(List<Integer> values) {
            addCriterion("buffer_net_remaining_quantity not in", values, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityBetween(Integer value1, Integer value2) {
            addCriterion("buffer_net_remaining_quantity between", value1, value2, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andBufferNetRemainingQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("buffer_net_remaining_quantity not between", value1, value2, "bufferNetRemainingQuantity");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtIsNull() {
            addCriterion("modified_at is null");
            return (Criteria) this;
        }

        public Criteria andModifiedAtIsNotNull() {
            addCriterion("modified_at is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedAtEqualTo(LocalDateTime value) {
            addCriterion("modified_at =", value, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtNotEqualTo(LocalDateTime value) {
            addCriterion("modified_at <>", value, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtGreaterThan(LocalDateTime value) {
            addCriterion("modified_at >", value, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("modified_at >=", value, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtLessThan(LocalDateTime value) {
            addCriterion("modified_at <", value, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("modified_at <=", value, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtIn(List<LocalDateTime> values) {
            addCriterion("modified_at in", values, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtNotIn(List<LocalDateTime> values) {
            addCriterion("modified_at not in", values, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("modified_at between", value1, value2, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andModifiedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("modified_at not between", value1, value2, "modifiedAt");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Boolean value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Boolean value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Boolean value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Boolean value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Boolean> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Boolean> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNull() {
            addCriterion("modified_by is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByIsNotNull() {
            addCriterion("modified_by is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByEqualTo(String value) {
            addCriterion("modified_by =", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotEqualTo(String value) {
            addCriterion("modified_by <>", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThan(String value) {
            addCriterion("modified_by >", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("modified_by >=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThan(String value) {
            addCriterion("modified_by <", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLessThanOrEqualTo(String value) {
            addCriterion("modified_by <=", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByLike(String value) {
            addCriterion("modified_by like", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotLike(String value) {
            addCriterion("modified_by not like", value, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByIn(List<String> values) {
            addCriterion("modified_by in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotIn(List<String> values) {
            addCriterion("modified_by not in", values, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByBetween(String value1, String value2) {
            addCriterion("modified_by between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andModifiedByNotBetween(String value1, String value2) {
            addCriterion("modified_by not between", value1, value2, "modifiedBy");
            return (Criteria) this;
        }

        public Criteria andFutureQuantityIsNull() {
            addCriterion("future_quantity is null");
            return (Criteria) this;
        }

        public Criteria andFutureQuantityIsNotNull() {
            addCriterion("future_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andFutureQuantityEqualTo(Integer value) {
            addCriterion("future_quantity =", value, "futureQuantity");
            return (Criteria) this;
        }

    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.characteristicvalueresiduacto
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}